require('plugins')
require('options')
require('neodev-config') -- must be set before lsp-config
require('lsp-config')
require('cmp-config')
require('tree-sitter-config')
require('lsp-saga-config')
require('telescope-config')
require('autopairs-config')
require('themes/newpaper')
require('keymaps')
require('gitsigns-config')
require('nvim-tree-config')
require('bufferline-config')
require('lualine-config')
require('treesitter-context-config')
require('dap-config')
require('pounce-config')
require('lsp-signature-config')
require('auto-session-config')
require('which-key-config')

